env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: 
  no-console: off
  prettier/prettier: error
  # import/prefer-default-export: off
  # '@typescript-eslint/no-unused-vars': warn
